# Generated by Django 4.2.19 on 2025-02-22 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hidden_Spot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=200)),
                ('selected_spots', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Itinerary',
        ),
    ]
